### ISSUE TITLE
Compatibility with Java 9

### ISSUE THREAD

**Issue by GiantTreeLP** [GiantTreeLP/bukkitdependencyloader#1]
Java 9 uses a new `ClassLoader`, the `java.base/jdk.internal.loader.ClassLoaders$AppClassLoader`. This class loader is incompatible with the old `URLClassLoader` and should be handled accordingly.

```
org.bukkit.plugin.InvalidPluginException: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1268]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1268]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1268]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [patched_1.12.2.jar:git-Paper-1268]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1268]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1268]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at com.github.gianttreelp.bukkitdependencyloader.DependencyLoaderPlugin$DependencyLoader.loadArtifactIntoClassPath(DependencyLoaderPlugin.java:408) ~[?:?]
        at com.github.gianttreelp.bukkitdependencyloader.DependencyLoaderPlugin$DependencyLoader.loadArtifact(DependencyLoaderPlugin.java:387) ~[?:?]
        at com.github.gianttreelp.bukkitdependencyloader.DependencyLoaderPlugin$DependencyLoader.loadArtifact(DependencyLoaderPlugin.java:360) ~[?:?]
        at com.github.gianttreelp.bukkitdependencyloader.DependencyLoaderPlugin.parseArtifact(DependencyLoaderPlugin.java:254) ~[?:?]
        at com.github.gianttreelp.bukkitdependencyloader.DependencyLoaderPlugin.loadArtifact(DependencyLoaderPlugin.java:177) ~[?:?]
        at com.github.gianttreelp.bukkitdependencyloader.DependencyLoaderPlugin.lambda$null$4(DependencyLoaderPlugin.java:165) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at com.github.gianttreelp.bukkitdependencyloader.DependencyLoaderPlugin.lambda$scanPluginsAndLoadArtifacts$5(DependencyLoaderPlugin.java:164) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at com.github.gianttreelp.bukkitdependencyloader.DependencyLoaderPlugin.scanPluginsAndLoadArtifacts(DependencyLoaderPlugin.java:144) ~[?:?]
        at com.github.gianttreelp.bukkitdependencyloader.DependencyLoaderPlugin.<init>(DependencyLoaderPlugin.java:105) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
        at java.lang.Class.newInstance(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:80) ~[patched_1.12.2.jar:git-Paper-1268]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1268]
        ... 6 more
[18:44:53 ERROR]: Could not load 'plugins\groundmc.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: BukkitDependencyLoader
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:218) [patched_1.12.2.jar:git-Paper-1268]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [patched_1.12.2.jar:git-Paper-1268]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1268]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1268]
        at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by GiantTreeLP** [comment]
Currently, there is no easy way of doing this in Java 9.
